version: '3'

services:
  symfony-demo-php:
    build:
      context: ./docker/php
    container_name: symfony-demo-php
    working_dir: /var/www
    user: 1000:1000
    volumes:
      - ./:/var/www
      - ./var/composer:/var/www/var/composer
    environment:
      COMPOSER_HOME: /var/www/var/composer
      XDEBUG_CONFIG: client_host=${DOCKER_GATEWAY_HOST:-host.docker.internal}
      PHP_IDE_CONFIG: serverName=symfony
    env_file:
      - .env
    depends_on:
      symfony-demo-rabbitmq:
        condition: service_healthy
      symfony-demo-postgres:
        condition: service_healthy

  symfony-demo-postgres:
    image: postgres:latest
    container_name: symfony-demo-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: demo
    volumes:
      - ./var/postgres-data:/var/lib/postgresql/data
    ports:
      - "54322:5432"
    restart: always
    healthcheck:
      test: pg_isready -U root -d demo -p 5432
      interval: 5s
      timeout: 5s
      retries: 10

  symfony-demo-nginx:
    container_name: symfony-demo-nginx
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./docker/nginx/config:/etc/nginx/templates
      - ./docker/nginx/logs:/var/log/nginx
    ports:
      - '8081:80'
      - '4434:443'
    depends_on:
      - symfony-demo-php
    env_file:
      - .env

  symfony-demo-rabbitmq:
    image: rabbitmq:3.8-management
    container_name: symfony-demo-rabbitmq
    volumes:
      - symfony-demo-rabbitmq-data:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  symfony-demo-rabbitmq-data: