version: '3'

services:
  symfony-demo-php:
    build:
      context: ./docker/php
    container_name: symfony-demo-php
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./var/composer:/var/www/var/composer
    environment:
      COMPOSER_HOME: /var/www/var/composer
      XDEBUG_CONFIG: client_host=${DOCKER_GATEWAY_HOST:-host.docker.internal}
      PHP_IDE_CONFIG: serverName=symfony
    env_file:
      - .env

  symfony-demo-postgres:
    image: postgres:latest
    container_name: symfony-demo-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: demo
    volumes:
      - ./var/postgres-data:/var/lib/postgresql/data
    ports:
      - "54322:5432"
    restart: always

  symfony-demo-nginx:
    container_name: symfony-demo-nginx
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./docker/nginx/config:/etc/nginx/templates
      - ./docker/nginx/logs:/var/log/nginx
    ports:
      - '8081:80'
      - '4434:443'
    depends_on:
      - symfony-demo-php
    env_file:
      - .env